
rule_files:
  - /etc/prometheus/alertmanager_rules.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ekyc_backend
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
