"""
Audit Export PDF Service - M31
Generates BFIU-compliant audit trail PDF reports.
BFIU Circular No. 29 - Section 5.1 (5-year retention requirement).
"""
import io
from datetime import datetime, timezone
from typing import Optional, List

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

# ── Brand colours ────────────────────────────────────────────────────────
ACCENT   = colors.HexColor("#6358ff")
GREEN    = colors.HexColor("#00b87a")
RED      = colors.HexColor("#f03d5f")
YELLOW   = colors.HexColor("#f0a500")
BG_LIGHT = colors.HexColor("#f4f4f8")
BG_DARK  = colors.HexColor("#e8e8f0")
BORDER   = colors.HexColor("#e2e2ea")
TEXT     = colors.HexColor("#1a1a2e")
TEXT2    = colors.HexColor("#6b6b8a")
WHITE    = colors.white

def _now():
    return datetime.now(timezone.utc)

def _styles():
    return {
        "title":    ParagraphStyle("title",    fontSize=16, textColor=ACCENT,
                                   fontName="Helvetica-Bold", spaceAfter=2, alignment=TA_CENTER),
        "subtitle": ParagraphStyle("subtitle", fontSize=8,  textColor=TEXT2,
                                   fontName="Helvetica", spaceAfter=0, alignment=TA_CENTER),
        "h2":       ParagraphStyle("h2",       fontSize=10, textColor=ACCENT,
                                   fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4),
        "h3":       ParagraphStyle("h3",       fontSize=9,  textColor=TEXT,
                                   fontName="Helvetica-Bold", spaceBefore=6, spaceAfter=3),
        "body":     ParagraphStyle("body",     fontSize=8,  textColor=TEXT,
                                   fontName="Helvetica", spaceAfter=2),
        "caption":  ParagraphStyle("caption",  fontSize=7,  textColor=TEXT2,
                                   fontName="Helvetica", spaceAfter=2),
        "mono":     ParagraphStyle("mono",     fontSize=7,  textColor=TEXT,
                                   fontName="Courier", spaceAfter=2),
        "footer":   ParagraphStyle("footer",   fontSize=7,  textColor=TEXT2,
                                   fontName="Helvetica", alignment=TA_CENTER),
    }

def _table(data, col_widths, header=True):
    t = Table(data, colWidths=col_widths)
    style = [
        ("FONTNAME",     (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",     (0,0), (-1,-1), 7),
        ("TEXTCOLOR",    (0,0), (-1,-1), TEXT),
        ("GRID",         (0,0), (-1,-1), 0.3, BORDER),
        ("LEFTPADDING",  (0,0), (-1,-1), 5),
        ("RIGHTPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING",   (0,0), (-1,-1), 3),
        ("BOTTOMPADDING",(0,0), (-1,-1), 3),
        ("ROWBACKGROUNDS",(0,1), (-1,-1), [colors.white, BG_LIGHT]),
    ]
    if header:
        style += [
            ("BACKGROUND",  (0,0), (-1,0), ACCENT),
            ("TEXTCOLOR",   (0,0), (-1,0), WHITE),
            ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",    (0,0), (-1,0), 8),
        ]
    t.setStyle(TableStyle(style))
    return t

def generate_audit_pdf(
    entries: List[dict],
    institution_id: Optional[str] = None,
    generated_by: str = "system",
    report_title: str = "Audit Trail Report",
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
) -> bytes:
    """
    Generate a BFIU-compliant audit trail PDF.
    Returns PDF bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        topMargin=1.5*cm, bottomMargin=2*cm,
    )
    S = _styles()
    now_str = _now().strftime("%Y-%m-%d %H:%M:%S UTC")
    story = []

    # ── Header ───────────────────────────────────────────────────────────
    story.append(Paragraph("Xpert Fintech Ltd.", S["title"]))
    story.append(Paragraph("eKYC Platform — Audit Trail Report", S["subtitle"]))
    story.append(Paragraph("BFIU Circular No. 29 — Section 5.1 Compliance", S["subtitle"]))
    story.append(Spacer(1, 0.3*cm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT))
    story.append(Spacer(1, 0.3*cm))

    # ── Report metadata ──────────────────────────────────────────────────
    meta_data = [
        ["Report Title",     report_title,         "Generated At",    now_str],
        ["Institution ID",   institution_id or "ALL", "Generated By", generated_by],
        ["Total Entries",    str(len(entries)),     "Retention",      "5 years (BFIU §5.1)"],
        ["Date From",        date_from or "All time", "Date To",      date_to or "Present"],
    ]
    meta_table = Table(meta_data, colWidths=[3.5*cm, 6*cm, 3*cm, 5.5*cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",    (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",    (0,0), (-1,-1), 8),
        ("FONTNAME",    (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME",    (2,0), (2,-1), "Helvetica-Bold"),
        ("TEXTCOLOR",   (0,0), (0,-1), TEXT2),
        ("TEXTCOLOR",   (2,0), (2,-1), TEXT2),
        ("TEXTCOLOR",   (1,0), (1,-1), TEXT),
        ("TEXTCOLOR",   (3,0), (3,-1), TEXT),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [BG_LIGHT, colors.white]),
        ("GRID",        (0,0), (-1,-1), 0.3, BORDER),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING",  (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.5*cm))

    # ── Event summary ────────────────────────────────────────────────────
    story.append(Paragraph("Event Summary", S["h2"]))
    event_counts = {}
    for e in entries:
        et = e.get("event_type", "UNKNOWN")
        event_counts[et] = event_counts.get(et, 0) + 1

    if event_counts:
        summary_data = [["Event Type", "Count"]]
        for et, count in sorted(event_counts.items(), key=lambda x: -x[1]):
            summary_data.append([et, str(count)])
        story.append(_table(summary_data, [13*cm, 5*cm]))
    else:
        story.append(Paragraph("No events recorded.", S["body"]))
    story.append(Spacer(1, 0.5*cm))

    # ── Audit entries ────────────────────────────────────────────────────
    story.append(Paragraph(f"Audit Log Entries ({len(entries)} total)", S["h2"]))

    if entries:
        log_data = [["#", "Timestamp", "Event Type", "Entity", "Actor ID", "Session ID"]]
        for i, e in enumerate(entries[:500], 1):  # cap at 500 rows for PDF size
            ts = str(e.get("timestamp", ""))[:19]
            log_data.append([
                str(i),
                ts,
                e.get("event_type", ""),
                e.get("entity_type", ""),
                (e.get("actor_id") or "")[:20],
                (e.get("session_id") or "")[:20],
            ])
        story.append(_table(log_data, [0.8*cm, 3.8*cm, 4*cm, 2.5*cm, 3.5*cm, 3.4*cm]))
        if len(entries) > 500:
            story.append(Paragraph(
                f"Note: Showing first 500 of {len(entries)} entries. "
                "Use CSV export for complete data.",
                S["caption"]
            ))
    else:
        story.append(Paragraph("No audit entries found for the selected filters.", S["body"]))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 0.2*cm))

    # ── Footer ───────────────────────────────────────────────────────────
    story.append(Paragraph(
        f"Xpert Fintech Ltd. — eKYC Platform | BFIU Circular No. 29 — Section 5.1 | "
        f"Generated: {now_str} | Confidential",
        S["footer"]
    ))

    doc.build(story)
    return buf.getvalue()


def generate_session_audit_pdf(session_id: str, entries: List[dict]) -> bytes:
    """Generate a single-session audit PDF."""
    return generate_audit_pdf(
        entries=entries,
        report_title=f"Session Audit Report — {session_id}",
        generated_by="system",
    )
