"""M53 adverse media rescan columns on kyc_profiles

Revision ID: 1e6df3c00319
Revises: 259fab2cedac
Create Date: 2026-04-23 16:08:43.951218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6df3c00319'
down_revision: Union[str, None] = '259fab2cedac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
