"""M40_postgresql_migration_baseline

Revision ID: 259fab2cedac
Revises: c28956d50a52
Create Date: 2026-04-20 02:25:25.946017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259fab2cedac'
down_revision: Union[str, None] = 'c28956d50a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
