"""M25_full_schema_all_modules

Revision ID: c28956d50a52
Revises: 
Create Date: 2026-04-19 02:19:58.965056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c28956d50a52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_institutions_client_id', table_name='institutions')
    op.drop_index('ix_institutions_status', table_name='institutions')
    op.drop_table('institutions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_institution_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_sessions_jti', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_agent_profiles_agent_code', table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('agent_code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('district', sa.VARCHAR(length=64), nullable=True),
    sa.Column('upazila', sa.VARCHAR(length=64), nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=20), nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=20), nullable=True),
    sa.Column('assigned_zone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_agent_profiles_agent_code', 'agent_profiles', ['agent_code'], unique=1)
    op.create_table('user_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('refresh_jti', sa.VARCHAR(length=36), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_jti')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_jti', 'user_sessions', ['jti'], unique=1)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('institution_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('totp_secret', sa.VARCHAR(length=64), nullable=True),
    sa.Column('totp_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('failed_login_count', sa.INTEGER(), nullable=False),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_institution_id', 'users', ['institution_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('institutions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('institution_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('client_secret_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('ip_whitelist', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('bfiu_threshold_overrides', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deactivated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('ix_institutions_status', 'institutions', ['status'], unique=False)
    op.create_index('ix_institutions_client_id', 'institutions', ['client_id'], unique=1)
    # ### end Alembic commands ###
